/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.14 public/covermodels/basketball.gltf -t -r public 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    Cube012: THREE.Mesh
    Cube012_1: THREE.Mesh
    Cube013: THREE.Mesh
    Cube013_1: THREE.Mesh
    Cube003: THREE.Mesh
    Torus009: THREE.Mesh
    Torus022: THREE.Mesh
    Torus022_1: THREE.Mesh
  }
  materials: {
    Brown: THREE.MeshStandardMaterial
    ['Black.002']: THREE.MeshStandardMaterial
    ['Blue.001']: THREE.MeshStandardMaterial
    ['White.002']: THREE.MeshStandardMaterial
    ['Yellow.002']: THREE.MeshStandardMaterial
    ['Red.002']: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Basketball(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/covermodels/basketball.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-0.024, 1.382, 0.406]} rotation={[-1.725, -0.339, -0.005]} scale={0.471}>
        <mesh geometry={nodes.Cube006.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials['Black.002']} />
      </group>
      <group position={[-0.087, 1.176, -0.217]} scale={[1.506, 1.448, 1.085]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials['Blue.001']} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['White.002']} />
      </group>
      <group position={[-0.087, 1.176, -0.217]} scale={[1.299, 1.448, 0.899]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['Yellow.002']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['White.002']} />
      </group>
      <mesh geometry={nodes.Cube003.geometry} material={materials['Red.002']} position={[-0.087, 0.643, -0.134]} scale={[0.257, 0.161, 0.017]} />
      <mesh geometry={nodes.Torus009.geometry} material={materials['Red.002']} position={[-0.087, 0.782, 0.49]} scale={1.736} />
      <group position={[-0.087, 0.784, 0.49]} rotation={[0, 0.297, 0]} scale={1.705}>
        <mesh geometry={nodes.Torus022.geometry} material={materials['White.002']} />
        <mesh geometry={nodes.Torus022_1.geometry} material={materials['Blue.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/covermodels/basketball.gltf')
